[env:gateway]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

lib_deps =
    jgromes/RadioLib @ ^6.6.0

upload_protocol = espota
upload_port = 10.107.167.140 ; Replace with your Gateway's IP address