[env:gateway]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

lib_deps =
    jgromes/RadioLib @ ^6.6.0
    bblanchon/ArduinoJson @ ^7.0.4

; upload_protocol = espota
; upload_port = 10.242.243.76 ; Replace with your Gateway's IP address